services:
  server:
    build:
      dockerfile: empstat-server/dockerfile
    environment:
      EMPSTAT_SERVER_PORT: 5000
      EMPSTAT_LOG_LEVEL: info
      EMPSTAT_NODE_ENV: debug
      EMPSTAT_DATABASE_URL: postgresql://developer:postpass@localhost:5432/empstat?schema=public
      EMPSTAT_ACCESS_TOKEN_SECRET: 02881a75691bca9fd2af5f475ae33a30673e48a475768ffaddf7b1b92898e85b3661c5b8afdf4b9afff6001fc45df6f34b2101423e865b4809413764d15812d9
      EMPSTAT_REFRESH_TOKEN_SECRET: b66ccd644eaeb9990c583a5ad66a69f202fa884eb30877f232ae533c6764289f2d968db3ee756d2827a09b4f4b75aa6d0320801c64fc1c154ad8eb0daa0f7c18
      EMPSTAT_ACCESS_TOKEN_EXPIRE_TIME: 1h
      EMPSTAT_PASSWORD_HASH_SALT_ROUNDS: 10
    ports:
      - 3000:3000
    depends_on:
      - db

  webapp:
    build:
      dockerfile: empstat-webapp/dockerfile
    environment:
      EMPSTAT_SERVER: localhost:3000
    ports:
      - 4000:4000
    depends_on:
      - server

  db:
    image: postgres:17
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: postpass
      POSTGRES_DB: empstat
    ports:
      - 5432:5432

  transformation:
    build:
      dockerfile: empstat-datatransform/dockerfile
    environment:
      EMPSTAT_DATABASE_URL: postgresql://developer:postpass@localhost:5432/empstat?schema=public
    depends_on:
      - db

volumes:
  db_data:
