services:
  server:
    build:
      context: empstat-server
      dockerfile: dockerfile
    environment:
      - EMPSTAT_SERVER_PORT
      - EMPSTAT_SERVER_LOG_LEVEL
      - EMPSTAT_SERVER_NODE_ENV
      - EMPSTAT_SERVER_ACCESS_TOKEN_SECRET
      - EMPSTAT_SERVER_REFRESH_TOKEN_SECRET
      - EMPSTAT_SERVER_ACCESS_TOKEN_EXPIRE_TIME
      - EMPSTAT_SERVER_PASSWORD_HASH_SALT_ROUNDS
      - EMPSTAT_DATABASE_URL=postgresql://${EMPSTAT_DATABASE_USER}:${EMPSTAT_DATABASE_PASSWORD}@database:${EMPSTAT_DATABASE_PORT}/${EMPSTAT_DATABASE_NAME}?schema=${EMPSTAT_DATABASE_SCHEMA}
    ports:
      - ${EMPSTAT_SERVER_PORT}:${EMPSTAT_SERVER_PORT}
    depends_on:
      - database

  webapp:
    build:
      context: empstat-webapp
      dockerfile: dockerfile
    environment:
      - REACT_APP_EMPSTAT_SERVER_URL=http://server:${EMPSTAT_SERVER_PORT}
      - PORT=${EMPSTAT_WEBAPP_PORT}
    ports:
      - ${EMPSTAT_WEBAPP_PORT}:${EMPSTAT_WEBAPP_PORT}
    depends_on:
      - server

  database:
    build:
      context: empstat-database
      dockerfile: dockerfile
    environment:
      - POSTGRES_USER=${EMPSTAT_DATABASE_USER}
      - POSTGRES_PASSWORD=${EMPSTAT_DATABASE_PASSWORD}
      - POSTGRES_DB=${EMPSTAT_DATABASE_NAME}
    ports:
      - ${EMPSTAT_DATABASE_PORT}:${EMPSTAT_DATABASE_PORT}
